---
- name: Configurazione Server UrBackup su Raspberry
  hosts: raspberry
  become: yes  # Esegue come sudo

  tasks:
    - name: Aggiorna i repository dei pacchetti
      apt:
        update_cache: yes

    - name: Installa Docker e le dipendenze
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Crea la cartella per il mount del disco da 1TB
      file:
        path: /mnt/backup_disk
        state: directory
        mode: '0755'

    - name: Avvia il servizio Docker
      service:
        name: docker
        state: started
        enabled: yes
